name: supply-chain
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - jupyterlab
  - matplotlib
  - seaborn
  - pyarrow
  - pytest
  - scikit-learn
  - xgboost
  - pip:
      - chronos-forecasting
